sudo: true
dist: trusty
language: c
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq binutils-dev binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu genisoimage liblzma-dev syslinux
script:
- "./script/prep-release.sh"
